# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  push-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate DO credentials
        run: bash ./scripts/build-digitalocean-creds
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Push changes
        run: bash ./dnscontrol push

      - name: Clean credentials
        run: rm -f ./creds.json
