# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate DO credentials
        run: bash ./scripts/build-digitalocean-creds
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Preview changes
        run: bash ./dnscontrol preview
        if: github.event_name == 'pull_request'

      - name: Push changes
        run: echo bash ./dnscontrol push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Clean credentials
        run: rm -f ./creds.json
